import type { Question } from "./types"

export const PRELOADED_QUESTIONS: Question[] = [
  // ── Behavioral (25) ───────────────────────────────────────────────────────
  { id: "b01", category: "behavioral", difficulty: "easy", question: "Tell me about yourself.", starTemplate: false },
  { id: "b02", category: "behavioral", difficulty: "easy", question: "Why do you want to work here?", starTemplate: false },
  { id: "b03", category: "behavioral", difficulty: "easy", question: "What are your greatest strengths?", starTemplate: false },
  { id: "b04", category: "behavioral", difficulty: "medium", question: "Tell me about a time you faced a challenging technical problem. How did you resolve it?", starTemplate: true },
  { id: "b05", category: "behavioral", difficulty: "medium", question: "Describe a situation where you had to work with a difficult team member.", starTemplate: true },
  { id: "b06", category: "behavioral", difficulty: "medium", question: "Tell me about a project you are most proud of.", starTemplate: true },
  { id: "b07", category: "behavioral", difficulty: "medium", question: "Describe a time you failed. What did you learn?", starTemplate: true },
  { id: "b08", category: "behavioral", difficulty: "medium", question: "How do you handle disagreements with your manager?", starTemplate: true },
  { id: "b09", category: "behavioral", difficulty: "medium", question: "Tell me about a time you had to meet a tight deadline.", starTemplate: true },
  { id: "b10", category: "behavioral", difficulty: "hard", question: "Describe a time you had to make a decision with incomplete information.", starTemplate: true },
  { id: "b11", category: "behavioral", difficulty: "hard", question: "Tell me about a time you influenced a major decision without formal authority.", starTemplate: true },
  { id: "b12", category: "behavioral", difficulty: "medium", question: "Give an example of a time you improved a process or system.", starTemplate: true },
  { id: "b13", category: "behavioral", difficulty: "medium", question: "Describe a situation where you had to quickly learn a new technology.", starTemplate: true },
  { id: "b14", category: "behavioral", difficulty: "easy", question: "Where do you see yourself in 5 years?", starTemplate: false },
  { id: "b15", category: "behavioral", difficulty: "medium", question: "How do you prioritize tasks when you have multiple competing deadlines?", starTemplate: true },
  { id: "b16", category: "behavioral", difficulty: "hard", question: "Describe a time you had to give difficult feedback to a colleague.", starTemplate: true },
  { id: "b17", category: "behavioral", difficulty: "medium", question: "Tell me about a time you went above and beyond for a customer or stakeholder.", starTemplate: true },
  { id: "b18", category: "behavioral", difficulty: "medium", question: "How do you stay updated with the latest technologies in your field?", starTemplate: false },
  { id: "b19", category: "behavioral", difficulty: "hard", question: "Describe a time you had to pivot strategy mid-project due to changing requirements.", starTemplate: true },
  { id: "b20", category: "behavioral", difficulty: "medium", question: "Tell me about your most impactful contribution at your last job.", starTemplate: true },
  { id: "b21", category: "behavioral", difficulty: "hard", question: "How have you handled a situation where your team was underperforming?", starTemplate: true },
  { id: "b22", category: "behavioral", difficulty: "medium", question: "Describe a time you built a strong relationship with a key stakeholder.", starTemplate: true },
  { id: "b23", category: "behavioral", difficulty: "easy", question: "How do you handle stress and pressure?", starTemplate: false },
  { id: "b24", category: "behavioral", difficulty: "medium", question: "Tell me about a time you received critical feedback. How did you respond?", starTemplate: true },
  { id: "b25", category: "behavioral", difficulty: "hard", question: "Describe the most complex project you have led from start to finish.", starTemplate: true },

  // ── System Design (20) ────────────────────────────────────────────────────
  { id: "sd01", category: "system-design", difficulty: "medium", question: "Design a URL shortener (like bit.ly).", tips: "Focus on read-heavy vs write-heavy, hashing, database choice" },
  { id: "sd02", category: "system-design", difficulty: "hard", question: "Design Twitter's news feed.", tips: "Fan-out on write vs read, caching, sharding" },
  { id: "sd03", category: "system-design", difficulty: "hard", question: "Design a distributed cache (like Redis).", tips: "Eviction policies, consistency, replication" },
  { id: "sd04", category: "system-design", difficulty: "medium", question: "Design a rate limiter.", tips: "Token bucket vs sliding window, Redis, distributed systems" },
  { id: "sd05", category: "system-design", difficulty: "hard", question: "Design WhatsApp (messaging at scale).", tips: "WebSockets, message storage, delivery receipts, group chats" },
  { id: "sd06", category: "system-design", difficulty: "hard", question: "Design YouTube.", tips: "CDN, video encoding, distributed storage, recommendation" },
  { id: "sd07", category: "system-design", difficulty: "medium", question: "Design a parking lot system.", tips: "OOP design, parking slots, payment, sensors" },
  { id: "sd08", category: "system-design", difficulty: "hard", question: "Design Google Search.", tips: "Web crawling, inverted index, PageRank, serving" },
  { id: "sd09", category: "system-design", difficulty: "medium", question: "Design a notification system.", tips: "Push vs pull, fanout, delivery guarantees" },
  { id: "sd10", category: "system-design", difficulty: "hard", question: "Design Uber's ride-matching system.", tips: "Geo-sharding, real-time location, matching algorithm" },
  { id: "sd11", category: "system-design", difficulty: "medium", question: "Design a key-value store.", tips: "LSM tree, WAL, compaction, consistency" },
  { id: "sd12", category: "system-design", difficulty: "hard", question: "Design a distributed message queue (like Kafka).", tips: "Topics, partitions, consumer groups, offset management" },
  { id: "sd13", category: "system-design", difficulty: "medium", question: "Design an API gateway.", tips: "Auth, rate limiting, routing, service discovery" },
  { id: "sd14", category: "system-design", difficulty: "hard", question: "Design Netflix's content delivery.", tips: "CDN, ABR streaming, cache placement, Open Connect" },
  { id: "sd15", category: "system-design", difficulty: "medium", question: "Design a live leaderboard.", tips: "Redis sorted sets, eventual consistency, scale" },
  { id: "sd16", category: "system-design", difficulty: "hard", question: "Design a distributed transaction system.", tips: "2PC, Saga pattern, ACID vs BASE" },
  { id: "sd17", category: "system-design", difficulty: "medium", question: "How would you design a search autocomplete system?", tips: "Trie, prefix cache, Elasticsearch" },
  { id: "sd18", category: "system-design", difficulty: "hard", question: "Design Instagram.", tips: "Photo storage, feed generation, social graph" },
  { id: "sd19", category: "system-design", difficulty: "medium", question: "Design a web crawler.", tips: "BFS, politeness policy, duplicate detection, storage" },
  { id: "sd20", category: "system-design", difficulty: "hard", question: "Design a real-time collaborative document editor (like Google Docs).", tips: "OT vs CRDT, conflict resolution, WebSockets" },

  // ── DSA (25) ──────────────────────────────────────────────────────────────
  { id: "dsa01", category: "dsa", difficulty: "easy", question: "Two Sum: Given an array of integers and a target, return indices of the two numbers that add up to target.", tips: "Use a hash map for O(n) solution" },
  { id: "dsa02", category: "dsa", difficulty: "easy", question: "Valid Parentheses: Given a string of brackets, determine if it's valid.", tips: "Use a stack" },
  { id: "dsa03", category: "dsa", difficulty: "medium", question: "Longest Substring Without Repeating Characters.", tips: "Sliding window with a set" },
  { id: "dsa04", category: "dsa", difficulty: "medium", question: "Binary Tree Level Order Traversal (BFS).", tips: "Use a queue, track level size" },
  { id: "dsa05", category: "dsa", difficulty: "medium", question: "Merge Intervals.", tips: "Sort by start, then merge overlapping" },
  { id: "dsa06", category: "dsa", difficulty: "hard", question: "Minimum Window Substring.", tips: "Sliding window, two pointers" },
  { id: "dsa07", category: "dsa", difficulty: "medium", question: "Number of Islands (DFS/BFS on grid).", tips: "Mark visited cells, 4-directional DFS" },
  { id: "dsa08", category: "dsa", difficulty: "easy", question: "Reverse a Linked List.", tips: "Iterative: prev, curr, next pointers" },
  { id: "dsa09", category: "dsa", difficulty: "medium", question: "Course Schedule (Topological Sort / cycle detection).", tips: "BFS Kahn's algorithm or DFS with states" },
  { id: "dsa10", category: "dsa", difficulty: "hard", question: "Word Ladder.", tips: "BFS with each character substitution as an edge" },
  { id: "dsa11", category: "dsa", difficulty: "medium", question: "Coin Change.", tips: "DP with bottom-up approach, dp[0]=0" },
  { id: "dsa12", category: "dsa", difficulty: "easy", question: "Climbing Stairs.", tips: "Fibonacci pattern, DP" },
  { id: "dsa13", category: "dsa", difficulty: "medium", question: "Find the kth largest element in an array.", tips: "Min-heap of size k, or QuickSelect O(n) average" },
  { id: "dsa14", category: "dsa", difficulty: "hard", question: "Serialize and Deserialize a Binary Tree.", tips: "BFS or DFS, use null markers" },
  { id: "dsa15", category: "dsa", difficulty: "medium", question: "3Sum: Find all triplets that sum to zero.", tips: "Sort + two pointers, skip duplicates" },
  { id: "dsa16", category: "dsa", difficulty: "medium", question: "Implement LRU Cache.", tips: "HashMap + doubly-linked list, O(1) all ops" },
  { id: "dsa17", category: "dsa", difficulty: "medium", question: "Pacific Atlantic Water Flow.", tips: "BFS from each ocean, find intersection" },
  { id: "dsa18", category: "dsa", difficulty: "easy", question: "Best Time to Buy and Sell Stock.", tips: "Track minimum price seen so far" },
  { id: "dsa19", category: "dsa", difficulty: "medium", question: "Subsets: Generate all subsets of a set.", tips: "Backtracking or bit manipulation" },
  { id: "dsa20", category: "dsa", difficulty: "hard", question: "Trapping Rain Water.", tips: "Two pointers from both ends, or precompute max left/right" },
  { id: "dsa21", category: "dsa", difficulty: "hard", question: "Median of Two Sorted Arrays.", tips: "Binary search on smaller array, O(log(min(m,n)))" },
  { id: "dsa22", category: "dsa", difficulty: "medium", question: "Explain time/space complexity of quicksort vs mergesort.", tips: "Average O(n log n) vs worst case, stability, in-place" },
  { id: "dsa23", category: "dsa", difficulty: "easy", question: "Detect a cycle in a linked list.", tips: "Floyd's tortoise and hare algorithm" },
  { id: "dsa24", category: "dsa", difficulty: "medium", question: "Longest Common Subsequence.", tips: "2D DP, dp[i][j] = LCS of first i, j chars" },
  { id: "dsa25", category: "dsa", difficulty: "hard", question: "Edit Distance (Levenshtein).", tips: "2D DP, three operations: insert, delete, replace" },

  // ── Culture Fit (15) ──────────────────────────────────────────────────────
  { id: "cf01", category: "culture-fit", difficulty: "easy", question: "What type of work environment do you thrive in?", starTemplate: false },
  { id: "cf02", category: "culture-fit", difficulty: "easy", question: "How do you prefer to receive feedback?", starTemplate: false },
  { id: "cf03", category: "culture-fit", difficulty: "easy", question: "What motivates you at work?", starTemplate: false },
  { id: "cf04", category: "culture-fit", difficulty: "medium", question: "How do you handle ambiguity and unclear requirements?", starTemplate: true },
  { id: "cf05", category: "culture-fit", difficulty: "medium", question: "Describe your ideal manager.", starTemplate: false },
  { id: "cf06", category: "culture-fit", difficulty: "easy", question: "What are your core values?", starTemplate: false },
  { id: "cf07", category: "culture-fit", difficulty: "medium", question: "How do you contribute to team culture?", starTemplate: true },
  { id: "cf08", category: "culture-fit", difficulty: "medium", question: "What does work-life balance mean to you?", starTemplate: false },
  { id: "cf09", category: "culture-fit", difficulty: "easy", question: "Why are you leaving your current position?", starTemplate: false },
  { id: "cf10", category: "culture-fit", difficulty: "medium", question: "How do you approach learning new skills?", starTemplate: false },
  { id: "cf11", category: "culture-fit", difficulty: "hard", question: "Tell me about a time company values conflicted with your personal values.", starTemplate: true },
  { id: "cf12", category: "culture-fit", difficulty: "easy", question: "What do you know about our company culture?", starTemplate: false },
  { id: "cf13", category: "culture-fit", difficulty: "medium", question: "How do you handle remote vs. in-office work preferences?", starTemplate: false },
  { id: "cf14", category: "culture-fit", difficulty: "medium", question: "What kind of problems are you most excited to solve?", starTemplate: false },
  { id: "cf15", category: "culture-fit", difficulty: "hard", question: "Describe how you would onboard to a new team and establish credibility quickly.", starTemplate: true },

  // ── Salary Negotiation (15) ───────────────────────────────────────────────
  { id: "sn01", category: "salary-negotiation", difficulty: "easy", question: "What are your salary expectations?", tips: "Give a range based on research, not a single number" },
  { id: "sn02", category: "salary-negotiation", difficulty: "medium", question: "Our budget is $X. Can you accept that?", tips: "Counter: 'I was hoping for $Y based on my research and experience'" },
  { id: "sn03", category: "salary-negotiation", difficulty: "hard", question: "We already gave you our best offer. There is no more room.", tips: "Negotiate non-salary: equity, signing bonus, vacation, remote days" },
  { id: "sn04", category: "salary-negotiation", difficulty: "medium", question: "How do you value equity vs. base salary?", tips: "Ask: strike price, preference shares, cliff/vesting schedule, 409A" },
  { id: "sn05", category: "salary-negotiation", difficulty: "easy", question: "Are you interviewing elsewhere?", tips: "Yes, being transparent about competing offers gives leverage" },
  { id: "sn06", category: "salary-negotiation", difficulty: "medium", question: "How do you know your market rate?", tips: "Levels.fyi, Glassdoor, Blind, LinkedIn salary, recruiter data" },
  { id: "sn07", category: "salary-negotiation", difficulty: "hard", question: "We need an answer by tomorrow. Can you decide?", tips: "It is okay to ask for 1 week to review the offer properly" },
  { id: "sn08", category: "salary-negotiation", difficulty: "medium", question: "We do not match competing offers.", tips: "Explain total comp difference, not just base, and what you value" },
  { id: "sn09", category: "salary-negotiation", difficulty: "easy", question: "What are your total compensation requirements?", tips: "Include base, bonus, equity, benefits in your answer" },
  { id: "sn10", category: "salary-negotiation", difficulty: "medium", question: "Is there anything other than salary that is important to you?", tips: "Remote flexibility, title, growth path, learning budget, PTO" },
  { id: "sn11", category: "salary-negotiation", difficulty: "hard", question: "What is the typical compensation range for someone at your experience level here?", tips: "Research before asking; this establishes anchoring" },
  { id: "sn12", category: "salary-negotiation", difficulty: "easy", question: "When were you last given a raise and how much was it?", tips: "Be honest, frame in terms of merit and market adjustment" },
  { id: "sn13", category: "salary-negotiation", difficulty: "medium", question: "Would you take a pay cut for the right opportunity?", tips: "Answer carefully; it can be used against you in negotiation" },
  { id: "sn14", category: "salary-negotiation", difficulty: "hard", question: "How do you justify asking for more than our posted range?", tips: "Rare specialized skills, competing offers, measurable impact" },
  { id: "sn15", category: "salary-negotiation", difficulty: "medium", question: "Do you have a signing bonus at your current company that would be forfeited?", tips: "Yes — ask the new company to cover it (clawback coverage)" },
]
